### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by jesusma32** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#11]
Hi ## Did you read the OpenCore Troubleshooting documentation?
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html

## System Specification
- CPU : the same
- MainBoard : the same
- Graphics : 

## Describe
I have black screen And no output

**Comment by lshbluesky** [comment]
Replace it with the Config.plist attached below and try rebooting.
[Config.plist.zip](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/files/9945451/Config.plist.zip)

**Comment by jesusma32** [comment]
Thanks, I change the same with Hackintool patch.  Do you have a laptop? Is for the Graphic card frame buffer. Thanks for your support

**Comment by lshbluesky** [comment]
I have a laptop with Intel 8th Gen KBL-R Core i5-8250U.
The Config.plist I gave in the comments above is a suitable setting for the Intel 7th Gen KBL desktop system using only iGPU.
