### ISSUE TITLE
Does not work with 10 bios version

### ISSUE THREAD

**Issue by masweb** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#2]
It seems very good configuration, too bad it doesn't work with bios version 10, can you test with that version ?

**Comment by lshbluesky** [comment]
Is your motherboard model name GA-B250M-DS3H correct?

When I checked on Gigabyte's official website, I couldn't find the BIOS update for the F10 version...
Only the F9 version is visible.
https://www.gigabyte.com/Motherboard/GA-B250M-DS3H-rev-10/support#support-dl-bios

Also, can you tell us in detail the situation of the problem where it won't boot?
Are you having trouble seeing the Mac OS Boot Entry?

**Comment by masweb** [comment]
Ok, sorry, is: HD3P
