### ISSUE TITLE
Doesn't load into installer

### ISSUE THREAD

**Issue by iyangsheng** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#24]
When loading into the installer, after the message "start::512: Successfully initialized AHCI controller" nothing happens for a while and then an error appears with blurry text (screenshots are attached).

![image](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/assets/39045336/d76adac9-a88a-4895-95f5-d694ad483b1f)
![image](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/assets/39045336/e3c0793a-9f1c-457f-be65-1bb3f54c53c1)

**Comment by iyangsheng** [comment]
Installed version macOS Ventura, Version: 13.4.1

**Comment by lshbluesky** [comment]
It is an error called `Still waiting for root device` and it is a USB related problem.
See the `Waiting for root device` section in OpenCore Troubleshooting.
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#waiting-for-root-device-or-prohibited-sign-error
