### ISSUE TITLE
Work on my B250M-D3V, But language force to Korean

### ISSUE THREAD

**Issue by stonexing** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#27]
Great project！👍👍👍
Language is hard to read, Please change to English.
or detect by system
using:
`<key>prev-lang:kbd</key>
                    <data></data>
`

1. During the installation I change Install language to Chinese.
2.After install completed. The system language is still Korean.

**Comment by lshbluesky** [comment]
1. Modify the `prev-lang:kbd` property to `en-US:0` and reboot.
2. Please refer to the site below and change the language in system settings.
https://support.apple.com/guide/mac-help/mh26684/mac
