### ISSUE TITLE
i7 7700 CPU

### ISSUE THREAD

**Issue by iyangsheng** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#3]
What needs to be changed for i7 7700 CPU

**Comment by iyangsheng** [comment]
我的屏幕卡在了“TCCD: Failed to route the function IsTypeCOnlySystem.”

![WechatIMG1](https://user-images.githubusercontent.com/39045336/116085785-c0ec0100-a6d1-11eb-8373-994002457781.jpeg)

**Comment by lshbluesky** [comment]
Did you set DVMT Pre Allocated Memory to 128 MB or more in BIOS settings?
I changed the values of framebuffer-stolenmem and framebuffer-fbmem properties a little higher in iGPU Properties, so you need to set DVMT Pre Allocated Memory to 128 MB.
If the capacity of (Stolen Mem + FB Mem) exceeds the capacity of DVMT Pre Allocated Memory, QE/CI graphics acceleration activation fails or booting fails.

Alternatively, add the -igfxvesa boot option to Config.plist and manually create and apply iGPU Properties after rebooting.

**Comment by iyangsheng** [comment]
Thank you. The problem has been solved. The configuration of config.plist is wrong
