### ISSUE TITLE
[Bug]Start up issue 

### ISSUE THREAD

**Issue by Invisiblearound** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#30]
## Did you read the OpenCore Troubleshooting documentation?
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html

## System Specification
- CPU : 
- MainBoard : OC-GA-B250M-DS3H
- Graphics : 

## Describe the problem
![Screen Shot 2024-01-21 at 10 13 54 AM](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/assets/62840373/49141380-2684-48af-9f60-625b807eb51e)

I have copied ur EFI folder and pasted inside EFI folder (not taken ACPI & OEM ACPI )

I just followed this video https://www.youtube.com/watch?v=JOZIPYhizK0

![issue](https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh/assets/62840373/403565e7-fe01-4a28-88f4-c5c87094394c)
## Additional Context

 Used 3.0 usb and also 2.0 usb

**Comment by lshbluesky** [comment]
Have you set XHCI Hand Off to Enabled in BIOS settings?
And, delete USBMap.kext and proceed with USB Port Mapping directly, or add USBToolBox.kext & UTBDefault.kext and reboot.

**Comment by Invisiblearound** [comment]
Thanks for reply,

XHCI Hand off is enabled

I have deleted USBMap.kext and tried not working 

I have added USBToolBox.kext & UTBDefault.kext  & reboot not working 

Removed USBMap.kext and added USBToolBox.kext & UTBDefault.kext not working 

Adding all and tried not working not working
