### ISSUE TITLE
No hdmi or dvi video

### ISSUE THREAD

**Issue by gara330** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#32]
## System Specification
- CPU : i7 7700 
- MainBoard : same
- Graphics : same

## Describe the problem
I have no video HDMI nor DVI, the only video output I have is from vga, it works perfectly with only one monitor, but I have a dual monitor septup

**Comment by lshbluesky** [comment]
Did you patch the connector yourself?
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html#parsing-the-framebuffer

**Comment by gara330** [comment]
I made it work patching the connector myself as you suggested, weird  thing, some times I have to disconnect and reconnect when I boot, thanks for the help

**Comment by lshbluesky** [comment]
> I made it work patching the connector myself as you suggested, weird thing, some times I have to disconnect and reconnect when I boot, thanks for the help

Try adding the `igfxonln=1` boot arg or force-online = 01000000 (Data) property.
