### ISSUE TITLE
Using with dedicated graphics cards

### ISSUE THREAD

**Issue by kapasifulop** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#37]
## System Specification
- CPU :  i5 7600k
- MainBoard :  GA-B250-HD3P
- Graphics : Asus Strix Radeon Vega 64

## Describe the problem
Can i use this EFI with a dedicated graphics card like Vega 64? Because I've tried to boot but i was stuck at the gigabyte logo.

**Comment by lshbluesky** [comment]
Yes, you can use it.
Please check the OpenCore boot log to see if there are any logs related to errors.

**Comment by kapasifulop** [comment]
Sorry, It was a bios setting.
