### ISSUE TITLE
I am anxiously awaiting the 0.68 - 11.3.1 update.

### ISSUE THREAD

**Issue by masweb** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#4]
Thanks to you, I can handle mac in the company, eternally grateful.

**Comment by masweb** [comment]
sorry

**Comment by lshbluesky** [comment]
Hello.
I recently updated OpenCore to the current latest version r0.7.1 and Kexts to the latest version as well.
The macOS Big Sur 11.4 update has also been successfully completed. 🙂
