### ISSUE TITLE
[problem]

### ISSUE THREAD

**Issue by zyh1993919** [lshbluesky/OC-GA-B250M-DS3H-Hackintosh#5]
## Did you read the OpenCore Troubleshooting documentation?
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html

## System Specification
- CPU : i5 7400
- MainBoard : Gigabyte GA-B250M-DS3H
- Graphics : HD630

## Describe the problem
hello，I am download this efi and only efi folder‘s files copy into u disk
my problem is how to use you efi and this pictures is report an error
![微信图片_20210804214426](https://user-images.githubusercontent.com/25995925/128191781-4f3d65ba-ae1a-42e9-9def-5bbfc9a27a5c.jpg)

## Additional Context
Thank you for checking this issue out of your busy schedule

**Comment by lshbluesky** [comment]
Hello.
Sorry for the late reply.

Only disable CpuTscSync.kext and try rebooting.

If that doesn't work, try disabling all ACPI Rename Patches, enabling only the following SSDT, and disabling other SSDTs.
- SSDT-EC-USBX.aml
- SSDT-HPET.aml
- SSDT-OSYS.aml
- SSDT-PLUG.aml
- SSDT-SBUS-MCHC.aml

**Comment by lshbluesky** [comment]
I will close this issue.
If you have any questions, please reopen or leave a comment.
